enum EventType {
  GET_TOKENS = "GET_TOKENS",
  SET_TOKENS = "SET_TOKENS",
  SET_COLOR_TOKEN = "SET_COLOR_TOKEN",
  UPDATE_COLOR_TOKEN = "UPDATE_COLOR_TOKEN",
  DELETE_COLOR_TOKEN = "DELETE_COLOR_TOKEN",
}

export default EventType;
